# Generated by Django 5.0.2 on 2024-03-14 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicles",
            fields=[
                (
                    "vehicleNumber",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("vehicleOwner", models.CharField(max_length=100)),
                ("vehicleManufacturer", models.CharField(max_length=50)),
                ("vehicleModel", models.CharField(max_length=50)),
                ("manufacturingYear", models.IntegerField()),
                ("color", models.CharField(max_length=50)),
            ],
        ),
    ]
