# Generated by Django 5.0.4 on 2024-04-05 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarRegistration',
            new_name='NewCarRegistration',
        ),
    ]
