# Generated by Django 5.0.2 on 2024-04-04 16:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_newcarregistration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newcarregistration",
            old_name="registered_by",
            new_name="register_name",
        ),
    ]
