# Generated by Django 5.0.4 on 2024-04-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_registeredcar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('vehicle_color', models.CharField(max_length=30)),
                ('model_number', models.CharField(max_length=50)),
                ('register_name', models.CharField(max_length=100)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='RegisteredCar',
        ),
    ]
